services:
  # Postgres database service
  # TODO: update db service to user golang backend
  recipevault-db:
    image: ${DOCKER_PROJECT_NAME}-db-img
    container_name: ${DOCKER_PROJECT_NAME}-db-container
    build:
      context: ./database
      dockerfile: ./.docker/Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -p $DB_PORT -d $DB_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - recipevault-network
    volumes:
      - postgres:/var/lib/postgresql/data

  # Postgres database migration/seed service
  recipevault-migrations:
      image: ${DOCKER_PROJECT_NAME}-migrations-img
      container_name: ${DOCKER_PROJECT_NAME}-migrations-container
      build:
        context: ./database
        dockerfile: ./.docker/Dockerfile.migrations
      environment:
        - NODE_ENV=${NODE_ENV}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER_API=${DB_USER_API}
        - DB_USER_API_PASSWORD=${DB_USER_API_PASSWORD}
      volumes:
        - /opt/database/node_modules # prevents local node_modules overriding container node_modules
      networks:
        - recipevault-network
      depends_on:
        recipevault-db:
          condition: service_healthy

  # API service
  recipevault-api:
      image: ${DOCKER_PROJECT_NAME}-api-img
      container_name: ${DOCKER_PROJECT_NAME}-api-container
      build:
        context: ./backend
        dockerfile: ./.docker/Dockerfile.api.dev
      ports:
        - ${API_PORT}:${API_PORT}
      environment:
        - APP_ENV=${NODE_ENV}
        - API_PORT=${API_PORT}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER_API=${DB_USER_API}
        - DB_USER_API_PASSWORD=${DB_USER_API_PASSWORD}
      volumes:
        - ./backend:/opt/backend
      networks:
        - recipevault-network
      depends_on:
        recipevault-migrations:
          condition: service_started

      command: 'air --build.cmd "go build -o bin/backend cmd/api/main.go" --build.bin "./bin/backend"'

  # APP service
  recipevault-app:
      image: ${DOCKER_PROJECT_NAME}-app-img
      container_name: ${DOCKER_PROJECT_NAME}-app-container
      build:
        context: ./app
        dockerfile: ./.docker/Dockerfile.app.dev
      ports:
        - ${APP_PORT}:${APP_PORT}
      environment:
        - NODE_ENV=${NODE_ENV}
        - VITE_APP_PORT=${APP_PORT}
        - VITE_API_URL=${API_URL}
      volumes:
        - ./app:/opt/app
        - /opt/app/node_modules # prevents local node_modules overriding container node_modules
      networks:
        - recipevault-network

networks:
  recipevault-network:
    driver: bridge

volumes:
  postgres:
    name: ${DOCKER_PROJECT_NAME}-db-vol
