version: "3.5"

services:
  # Postgres database service
  db:
    image: ${DOCKER_PROJECT_NAME}-db-img
    container_name: ${DOCKER_PROJECT_NAME}-db-container
    build:
      context: ./database
      dockerfile: ./.docker/Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -p $DB_PORT -d $DB_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - recipehub-network
    volumes:
      - postgres:/var/lib/postgresql/data

  # Postgres database migration/seed service
  migrations:
      image: ${DOCKER_PROJECT_NAME}-migrations-img
      container_name: ${DOCKER_PROJECT_NAME}-migrations-container
      build:
        context: ./database
        dockerfile: ./.docker/Dockerfile.migrations
      environment:
        - NODE_ENV=${NODE_ENV}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER_API=${DB_USER_API}
        - DB_USER_API_PASSWORD=${DB_USER_API_PASSWORD}
      volumes:
        - /opt/database/node_modules # prevents local node_modules overriding container node_modules
      networks:
        - recipehub-network
      depends_on:
        db:
          condition: service_healthy

  # API service
  api:
      image: ${DOCKER_PROJECT_NAME}-api-img
      container_name: ${DOCKER_PROJECT_NAME}-api-container
      build:
        context: ./api
        dockerfile: ./.docker/Dockerfile.api
      environment:
        - NODE_ENV=${NODE_ENV}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER_API=${DB_USER_API}
        - DB_USER_API_PASSWORD=${DB_USER_API_PASSWORD}
        - API_PORT=${API_PORT}
      volumes:
        - ./api:/opt/api
        - /opt/api/node_modules # prevents local node_modules overriding container node_modules
      networks:
        - recipehub-network
      command: ['npm', 'run', 'dev']

networks:
  recipehub-network:
    driver: bridge

volumes:
  postgres:
    name: ${DOCKER_PROJECT_NAME}-db-vol
