name: golangci-lint

on: [push]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.

  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: true
          cache-dependency-path: '**/go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: ./backend
